common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password: 170208

development:
  <<: *common
  database: lirary_development

test:
  <<: *common
  database: lirary_test

staging:
  <<: *common
  database: lirary_staging

production:
  <<: *common
  database: lirary